version: '3.2'

services:
    discoveryservice:
        build:
            context: DiscoveryService/
        ports:
            - "8761:8761"
        expose: 
            - "8761"
        networks:
            - intra
        
    configservice:
        build:
            context: ConfigService/
        volumes: 
            - ~/.ssh:/tmp/.ssh
        ports:
            - "8888:8888"
        expose: 
            - "8888"
        networks:
            - intra
        links: 
            - discoveryservice:discoveryservice
        depends_on:
        - discoveryservice

    routingservice:
        build:
            context: RoutingService/
        ports:
            - "8762:8762"
        expose: 
            - "8762"
        networks:
            - intra
        links: 
            - discoveryservice:discoveryservice
        depends_on:
            - discoveryservice

networks:
    intra:   
        driver: bridge