server:
    port: 8888
    http2:
        enabled: true
    compression:
        enabled: true

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    uri: git@github.com:marco-aurelioo/config-server-platform.git
                    user: marco-aurelioo
                    private_key_file: ~.ssh/id_rsa.pub
                    strictHostKeyChecking: false
    security:
        enabled: false
        user:
            name: root
            password: s3cr3t

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://discoveryservice:8761/eureka}