server:
    port: 8761
    http2:
        enabled: true
    compression:
        enabled: true
error:
    whitelabel:
        enabled: false
  
spring:
    application:
        name: eureka-server
  
  #Eureka Specifics
eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

